---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box
    customize:
      cpus: 2
      memory: 1024

suites:
- name: default
  run_list:
    - recipe[ktc-testing]
    - recipe[sensu::default]
    - recipe[collectd::client]
    - recipe[ktc-logging::server_logstash]
    - recipe[ktc-logging::server_es]
  attributes: 
    logging:
      recipes_server_logstash: 
        - ktc-logging::logstash
      recipes_server_es: 
        - elasticsearch::default
        - logstash::index_cleaner
      server: 
        logstash_processes:
          - { 
              name: "java", 
              shortname =>  "java" 
            }
        es_processes:
          - { 
              name: "java", 
              shortname: "java" 
            }
          - { 
              name:  "apache2", 
              shortname: "apache2" 
            }
        kibana_processes: 
          - {}
    logstash:
      elasticsearch_cluster: 'es-cluster-test'
    elasticsearch:
      cluster:
        name: 'es-cluster-test'

clusters:
  default:
    - default
